version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prom_vol:/etc/prometheus/
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000


volumes:
  prom_vol:
